/**
 * Animal API
 * blabla
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse200HydraSearchHydraMapping { 
    type?: string;
    variable?: string;
    property?: string | null;
    required?: boolean;
}

